repos:
  - repo: https://github.com/AleksaC/terraform-py
    rev: v1.9.5
    hooks:
      - id: tf-fmt
      - id: tf-validate
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.2'  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["--without-hashes", "-f", "requirements.txt", "-o", "./requirements.txt"]
      - id: poetry-install
